### ISSUE TITLE
请问这里的索引是否应该是 $i - 1 ? 

### ISSUE THREAD

**Issue by Saltedf** [satanson/cpp_etudes#28]
https://github.com/satanson/cpp_etudes/blob/a9c519191c7d315d3c17e73907bab0466c2a1ea0/calltree.pl#L626 

如果我没理解错的话, 这里的四元组中的第三个元素是函数定义的最后一行, 按这样理解这里的一行应该是: 

```perl
 push @result, [ $prev_file, $prev_lineno, $three_parts[$i-1][1], $prev_line ]; 
```

否则将会产生下面这样的四元组: 
```
jute/inc/EIndex.hh, 32, 24,        virtual ~EIndex() {} 
```
而修改后:  
```
jute/inc/EIndex.hh, 32, 32,        virtual ~EIndex() {} 
```

**Comment by satanson** [comment]
merge_lines_multiline_break_disabled 这个函数, 存在这样的问题. 后续在ag中，增加了multiline-break之后, 该函数不在使用.  你可以尝试一下https://github.com/satanson/the_silver_searcher.
