### ISSUE TITLE
[feature request] Whether recursive functions can be highlighted

### ISSUE THREAD

**Issue by LiuYinCarl** [satanson/cpp_etudes#29]
I use calltree.el in reading some open source software. It's an amazing art work, but I think there are some features can make it better, here are two suggestions.

1. The caller function marked in another color(like blue) or use a special word to mark it in mode 1, just like mode 0.

![image](https://user-images.githubusercontent.com/29608850/234649826-a3580c26-263d-4d17-848f-1fac9b9bbb49.png)

2. Provide an option argument to make recursive function call chain only appear once, in below picture, the call chain `recur_func3 -> recur_func2 -> recur_func3` appera twice. 

![image](https://user-images.githubusercontent.com/29608850/234650432-0b7be428-8ca0-42e8-b5de-a53042d80ce9.png)

3. After the source code change, auto regenerate the cpptree cache.

4. Provide an option argument to set the `.calltree.result.cached*` files directory but not just save them in the same dir of `calltree.pl`.

 test code for 1 and 2.

``` c
// rc.h
void recur_func1();

void recur_func2();

void recur_func3();
```

```c
// rc.c
#include "rc.h"

void recur_func1() {
  recur_func2();
  recur_func1();
}

void recur_func2() {
  recur_func3();
}

void recur_func3() {
  recur_func1();
}
```

**Comment by satanson** [comment]
@LiuYinCarl 
1. do you mean use a special color for callee or caller function in mode 1?  for mode 1,  in the call chain, all functions except the first one are all callers.
2. please re-try `calltree.pl 'recur_func1' '' 1 1 -9`, giving a negative depth will make some duplicate recursive patterns fold.
3. it is quite easy to implement this feature, use cpio or cat to concatenate the source files together then compute a fingerprint which can indicates code modifcation.
4. it is a good suggestion.

**Comment by LiuYinCarl** [comment]
@satanson 
> do you mean use a special color for callee or caller function in mode 1? for mode 1, in the call chain, all functions except the first one are all callers.

Yes, I mean if use `./calltree.pl 'recur_func1' '' 1 0 9`, I hope all the string `recur_func1` in the call tree is marked in a special color, so the users can quickly know which call chains is recursive call chain.
