### ISSUE TITLE
How to quickly execute a command like "[vim src/net/tls.cc +55]" in the output

### ISSUE THREAD

**Issue by erjiajigong** [satanson/cpp_etudes#30]
There are command like [vim src/net/tls.cc +55] in calltree.pl output
How did you perform it and what tools/methods you used

Can I click to execute it？Or can I only copy-paste to execute it?
Windows Terminal (ssh to Ubuntu) does not recognize this command in the output and cannot be directly clicked to execute.

Output like src/net/tls.cc:55 can be recognized by the terminal in vscode, click to jump to the corresponding location.

**Comment by satanson** [comment]
In ubuntu, vim should be installed(sudo apt-get install vim), paste the command in the terminal and then press enter.
